### ISSUE TITLE
Component Not Rendering Properly 

### ISSUE THREAD

**Issue by arthuruwalaka** [zorapeteri/react-tweet-card#4] opened 2022-12-25 06:38 UTC
Hey, 

I am trying to use the library for the first time. Testing it with the first example on the docs,  the component is not responsive and doesn't grow if the tweet is too long.

![Screen Shot 2022-12-24 at 11 26 29 PM](https://user-images.githubusercontent.com/55423381/209459007-681f369e-19a4-4e82-9288-7e1dc5d95727.png)

**Comment by zorapeteri** [comment] 2022-12-25 10:09
Hey @arthuruwalaka,

Could you please share some more info about your environment (e.g. React version, bundler, browser)?

**Comment by arthuruwalaka** [comment] 2022-12-25 17:55
@zorapeteri 

I am using React 18.2.0, webpack 5.75.0, webpack-bundle-tracker  ^1.7.0. I am also running it on chrome. I had to use --force flag to npm install the library.  

I am creating the component like this and just placing it in a div in an empty component. 

`

        import React, { Component } from "react";       
        import TweetCard from "react-tweet-card";
        
        class Tweet extends Component {
	        constructor(props) {
		        super(props);
		        this.state = {};
	        }
        
	        render() {
		        return (
			        <TweetCard
				        author={{
					        name: "randy",
					        username: "randyfactory",
					        image: "https://pbs.twimg.com/profile_images/1382083582752096262/xrx0PO8Z_400x400.jpg",
				        }}
				        tweet={`how was “philosopher” ever a job lmao like was socrates sippin wine on a balcony somewhere 
                                                        drunkenly slurring shit like “to find urself, think for urself” with a crowd cheering underneath him 
                                                         like fuck yes socrates another banger this man will not miss`}
				        time={new Date(2021, 2, 2, 21, 3)}
				        source="Twitter for iPhone"
				        permalink="https://twitter.com/randyfactory/status/1366841622495961091" // optional
				        fitInsideContainer
			        />
		        );
	        }
        }
        
        export default Tweet;
`

**Comment by zorapeteri** [comment] 2022-12-25 18:27
@arthuruwalaka 

I can see that with react@18.2.0 the peer dependency messes up the npm install, I will look into this, thanks for flagging.

I couldn't reproduce the output on your screenshot, could you perhaps try to make it happen in a [codesandbox](https://codesandbox.io/s/)?

**Comment by arthuruwalaka** [comment] 2022-12-25 19:02
@zorapeteri 

I tried it on code sandbox, and it works fine. https://codesandbox.io/live/60216be4869

**Comment by zorapeteri** [comment] 2022-12-25 19:20
In that case could you please share more about what you're doing exactly, maybe any webpack plugins you might have interfering. If you could share a live online copy of what you're working on would be great too so I could try and debug.

**Comment by arthuruwalaka** [comment] 2022-12-27 00:30
@zorapeteri 

https://github.com/arthuruwalaka/react-tweet-card. This is a copy of the project I am working on. You can run it on your local machine with npm start. I noticed that when I remove the <Home/> component import and the home route in App.js, the tweet texts seem to render fine. I am trying to figure out what may be causing the issue. Can you please take a look? The tweet card is being rendered in the <Temp/> component

**Comment by zorapeteri** [comment] 2022-12-28 11:03
Hey @arthuruwalaka,

I took a look at your code and at [header.scss:18](https://github.com/arthuruwalaka/react-tweet-card/blob/main/client/src/Components/header/header.scss#L18) you're setting a line height for all `p` tags, this gets applied to the one in the tweet card as well and breaks the text wrapping.
I would suggest changing that selector to `.header p` and you should be good to go.
Please close the issue if this fully solves it.

**Closed as completed** 2022-12-28 23:59 UTC
